### ISSUE TITLE
Done any work on this? Interested in collab?

### ISSUE THREAD

**Issue by kylebrowning** [moritzsternemann/nio-apns#1]
Ive started my own implementation of this and would love to collaborate with someone. 

Specifically doing an http/2 nio where you can simply process apns

**Comment by moritzsternemann** [comment]
Hey there, I started working on this as well based on [moritzsternemann/nio-h2](https://github.com/moritzsternemann/nio-h2).

I'm open for a collaboration. What's your current state?

**Comment by kylebrowning** [comment]
Nice I noticed that.

I currently have a Swift NIO HTTP2 procedural client (Not in any classes or abstracted), it generates the JSON web token using code I've ripped out of this, https://github.com/ethanhuang13/CupertinoJWT (since it doesn't have a `.package`).

It's officially posting push notifications to devices, my next step was to build a Vapor server to handle the registration of device tokens and pub sub models, but really needed a client to be working outside of Vapor since it doesn't support http/2 built in, and has no clients yet.

Let me clean up main.swift and show you.

**Comment by moritzsternemann** [comment]
Pushed my current working state for you to take a look :)

**Comment by kylebrowning** [comment]
https://gist.github.com/kylebrowning/db55ea542e397c7c096e2ea54dcfa061

Its mostly a consolidation of example code ive found everywhere, but your implementation looks a lot cleaner. 

Where are you handling the signing of the .p8 file?

**Comment by moritzsternemann** [comment]
That's the difference, mine is looking pretty and yours is actually working 😂 
There is not much functionality yet because I thought a lot about the right architecture.

**Comment by kylebrowning** [comment]
I’ll submit a PR. :)

**Comment by kylebrowning** [comment]
Turns out this won't work on linux so let me do it with openssl libs.
Closing this, but are you on slack or discord anywhere?

**Comment by moritzsternemann** [comment]
Not on any related channels or servers. Any suggestions?
I added you as a collaborator so working on this together is easier. Just create a new branch for your stuff. I'll try to get back to the project today or tomorrow
Edit: Started with payload serialisation on the develop branch

**Comment by kylebrowning** [comment]
@moritzsternemann Im on vapor discord (https://discord.gg/vapor username: ocyrus#5962) we could chat there, or I could invite you to my personal slack. up to you!

**Comment by kylebrowning** [comment]
Also on SwiftTalk, https://discord.gg/eSX9Dv if you don't want to join Vapor.
